---
title: "python_script_regressao"
author: "Mikael"
date: '2022-04-27'
output: html_document
---

```{r setup, include=FALSE}
library(reticulate)
# working_dir <- getwd() no RMD ele vai ler a pasta que está, então só vai funcionar se estiver na raiz
working_dir <- "/mnt/dados/Mikael/Projetos/Scripts_R/udemy-machinelearning-a-z/"
reticulate::use_virtualenv(paste0(working_dir, ".venv/"))
```

```{python}
## Importando bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
```

```{python}
## Lendo dados e limpando/ajustando NAs

df = pandas.read_csv("/mnt/dados/Mikael/Projetos/Scripts_R/udemy-machinelearning-a-z/R/1 - Limpeza e leitura da base/Data.csv")

#x = df.iloc[:, 0:3]
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

## Tratando dados faltantes
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
X
```

```{r}
View(py.X.head())
```