---
title: "Regressão linear múltipla"
author: "Mikael"
date: '2022-04-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 0 Leitura de bibliotecas e da base

```{r results = 'hide', warning=FALSE, message=FALSE}
# 0. Bibliotecas e scripts base ----
library(dplyr)
require(ggplot2)

```
## 1. Leitura e manipulação da base

### 1.1 Leitura
```{r results = 'hide', warning=FALSE, message=FALSE}

df <- read.csv("50_Startups.csv")
```

### 1.2
```{r results = 'hide', warning=FALSE, message=FALSE}
## variavel dependente
unique_y <- unique(df$State)
df$State = factor(df$State,
                  levels = unique_y,
                  # levels = c("France", 'Spain', 'Germany'),
                  labels = 1:(length(unique_y)))
```

## 2 Criando modelo

### 2.1 Divisão de treino e teste

```{r results = 'hide', warning=FALSE, message=FALSE}

library(caTools)

set.seed(seed = 123)

split = sample.split(df$Profit, SplitRatio = .8)
training_set <- subset(df, split == TRUE)
test_set <- subset(df, split == F)
```

### 2.2 Featuring scale - Adaptando escalas

```{r results = 'hide', warning=FALSE, message=FALSE}
# training_set[,2:3] <- scale(training_set[,2:3])
# test_set[,2:3] <- scale(test_set[,2:3])
```

### 2.3 Regresão linear ----

```{r results = 'hide', warning=FALSE, message=FALSE}
regressor <- lm(formula = Salary ~ YearsExperience, training_set)

## 2.4 Predição no grupo de teste ----
y_pred <- predict(regressor, newdata = test_set)

test_set[,3] = y_pred

test_set <- test_set |> 
  dplyr::rename(`Salary(y)` = Salary, `Salary(yp)` = V3)
```

### 2.5 Gráficos dedo modelo ----

```{r results = 'hide', warning=FALSE, message=FALSE}

plot <- ggplot2::ggplot(data = training_set) +
  geom_point(aes(x = YearsExperience, y = Salary),
             colour = 'red') +
  geom_line(data = training_set, aes(x = YearsExperience,
                                     y = predict(regressor, newdata = training_set)),
            color = 'blue') +
  scale_y_continuous(labels = scales::label_number_si()) +
  xlab('Anos de experiência') +
  ylab('Salário') +
  ggtitle("Salário vs Experiência (Regressão linear para base de treino)") +
  theme_minimal()

plot

plot_test <- ggplot2::ggplot(data = test_set) +
  geom_point(aes(x = YearsExperience, y = `Salary(y)`),
             colour = 'red') +
  geom_line(data = training_set, aes(x = YearsExperience,
                                     y = predict(regressor, newdata = training_set)),
            color = 'blue') + 
  scale_y_continuous(labels = scales::label_number_si()) +
  theme(axis.title.x = 'Anos de experiência', axis.title.y = 'Salário', ) +
  ggtitle("Salário vs Experiência (Regressão linear para base de teste)") +
  theme_minimal()
  
plot_test
```